# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x000000ff
bordercolor = 0x889392ff
dropcolor = 0x80d5d480
splitcolor = 0xb3c8e8ff
focuscolor = 0x80d5d4ff
maximizescreencolor = 0xb0cccbff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xb3c8e8ff
globalcolor = 0x004f50ff
overlaycolor = 0x324b4bff
jump_label_decorate_fg_color = 0xdde4e3ff
jump_label_decorate_bg_color = 0x181e1eff
jump_label_decorate_focus_fg_color = 0x003737ff
jump_label_decorate_focus_bg_color = 0x80d5d4ff
jump_label_decorate_border_color = 0x889392ff
group_bar_decorate_fg_color = 0xdde4e3ff
group_bar_decorate_bg_color = 0x181e1eff
group_bar_decorate_focus_fg_color = 0x003737ff
group_bar_decorate_focus_bg_color = 0x80d5d4ff
group_bar_decorate_border_color = 0x889392ff
