windowrule=isfloating:1,isglobal:1,width:900,height:600,appid:satty
windowrule=isfloating:1,width:1200,height:800,appid:pavucontrol
windowrule=isfloating:1,width:1200,height:800,appid:blueman-manager
windowrule=isfloating:1,width:1000,height:800,appid:org.gnome.gThumb
windowrule=isfloating:1,width:1000,height:800,appid:org.gnome.FileRoller
windowrule=isfloating:1,width:1000,height:800,appid:org.pwmt.zathura
windowrule=tags:4,appid:org.kde.dolphin
windowrule=isfloating:1,width:500,height:150,appid:org.kde.dolphin,title:Rename.*

#dolphin
windowrule=focused_opacity:0.88,unfocused_opacity:0.82,appid:org.kde.dolphin
# windowrule=blur:1,appid:org.kde.dolphin

#FileRoller
windowrule=focused_opacity:0.88,unfocused_opacity:0.82,appid:org.gnome.FileRoller
# windowrule=blur:1,appid:org.gnome.FileRoller

windowrule=focused_opacity:0.88,unfocused_opacity:0.82,appid:org.gnome.Calculator

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile



# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
