"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
$directory\
[](fg:#f9e2af bg:#a6e3a1)\
$git_branch$git_status\
[](fg:#a6e3a1 bg:#94e2d5)\
$nodejs$python$rust$golang$lua$c\
[](fg:#94e2d5 bg:#89b4fa)\
$package\
[](fg:#89b4fa bg:#cba6f7)\
$cmd_duration\
[](fg:#cba6f7 bg:#f5c2e7)\
[ $time ](bg:#f5c2e7 fg:#1e1e2e)\
[](fg:#f5c2e7 bg:#585b70)\
[](fg:#585b70 bg:#45475a)\
[](fg:#45475a bg:#313244)\
[](fg:#313244)
$character"""

command_timeout = 1000
add_newline = true

[os]
disabled = false
style = "bg:#fab387 fg:#1e1e2e bold"

[os.symbols]
Arch = "󰣇"
Ubuntu = ""
Debian = ""
Windows = "󰍲"
Macos = "󰀵"

[directory]
style = "bg:#f9e2af fg:#1e1e2e bold"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bg:#a6e3a1 fg:#1e1e2e bold"
format = "[  $branch ]($style)"

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = "[$all_status$ahead_behind ]($style)"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ "
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
deleted = "✘${count} "

[nodejs]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[python]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[rust]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[golang]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[lua]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[c]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[package]
style = "bg:#89b4fa fg:#1e1e2e bold"
format = "[ 󰏗 $version ]($style)"

[cmd_duration]
min_time = 500
style = "bg:#cba6f7 fg:#1e1e2e bold"
format = "[ 󱦟 $duration ]($style)"

[time]
disabled = false
style = "bg:#f5c2e7 fg:#1e1e2e bold"
format = "$time"
time_format = "%I:%M %p"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
vimcmd_symbol = "[❮](bold #f9e2af)"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#ecb8cd"
red       = "#ffb4ab"
green     = "#c8bfff"
yellow    = "#c9c3dc"
cyan      = "#c9c3dc"
magenta   = "#c8bfff"
white     = "#e2e2e2"
black     = "#474747"

# Extended palette (Catppuccin-compatible names)
rosewater = "#c9c3dc"
flamingo  = "#ffb4ab"
pink      = "#c8bfff"
mauve     = "#c8bfff"
maroon    = "#ffb4ab"
peach     = "#c9c3dc"
teal      = "#c9c3dc"
sky       = "#c9c3dc"
sapphire  = "#ecb8cd"
lavender  = "#c8bfff"

# Text shades
text      = "#e2e2e2"
subtext1  = "#e2e2e2"
subtext0  = "#919191"

# Surface shades
overlay2  = "#919191"
overlay1  = "#919191"
overlay0  = "#474747"
surface2  = "#474747"
surface1  = "#474747"
surface0  = "#000000"
base      = "#000000"
mantle    = "#000000"
crust     = "#000000"
# <<< NOCTALIA STARSHIP PALETTE <<<
