"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
$directory\
[](fg:#f9e2af bg:#a6e3a1)\
$git_branch$git_status\
[](fg:#a6e3a1 bg:#94e2d5)\
$nodejs$python$rust$golang$lua$c\
[](fg:#94e2d5 bg:#89b4fa)\
$package\
[](fg:#89b4fa bg:#cba6f7)\
$cmd_duration\
[](fg:#cba6f7 bg:#f5c2e7)\
[ $time ](bg:#f5c2e7 fg:#1e1e2e)\
[](fg:#f5c2e7 bg:#585b70)\
[](fg:#585b70 bg:#45475a)\
[](fg:#45475a bg:#313244)\
[](fg:#313244)
$character"""

command_timeout = 1000
add_newline = true

[os]
disabled = false
style = "bg:#fab387 fg:#1e1e2e bold"

[os.symbols]
Arch = "󰣇"
Ubuntu = ""
Debian = ""
Windows = "󰍲"
Macos = "󰀵"

[directory]
style = "bg:#f9e2af fg:#1e1e2e bold"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bg:#a6e3a1 fg:#1e1e2e bold"
format = "[  $branch ]($style)"

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = "[$all_status$ahead_behind ]($style)"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ "
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
deleted = "✘${count} "

[nodejs]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[python]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[rust]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[golang]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[lua]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[c]
style = "bg:#94e2d5 fg:#1e1e2e bold"
format = "[  $version ]($style)"

[package]
style = "bg:#89b4fa fg:#1e1e2e bold"
format = "[ 󰏗 $version ]($style)"

[cmd_duration]
min_time = 500
style = "bg:#cba6f7 fg:#1e1e2e bold"
format = "[ 󱦟 $duration ]($style)"

[time]
disabled = false
style = "bg:#f5c2e7 fg:#1e1e2e bold"
format = "$time"
time_format = "%I:%M %p"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
vimcmd_symbol = "[❮](bold #f9e2af)"














# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#a6c8ff"
red       = "#ffb4ab"
green     = "#bcc7dc"
yellow    = "#dabde2"
cyan      = "#bcc7dc"
magenta   = "#a6c8ff"
white     = "#e3e2e6"
black     = "#121316"

# Extended palette (Catppuccin-compatible names)
rosewater = "#dabde2"
flamingo  = "#dabde2"
pink      = "#a6c8ff"
mauve     = "#205fa6"
maroon    = "#ffb4ab"
peach     = "#dabde2"
teal      = "#bcc7dc"
sky       = "#bcc7dc"
sapphire  = "#bcc7dc"
lavender  = "#205fa6"

# Text shades
text      = "#e3e2e6"
subtext1  = "#c3c6cf"
subtext0  = "#8d9199"

# Surface shades
overlay2  = "#8d9199"
overlay1  = "#c3c6cf"
overlay0  = "#43474e"
surface2  = "#43474e"
surface1  = "#121316"
surface0  = "#121316"
base      = "#121316"
mantle    = "#121316"
crust     = "#3d2846"
# <<< NOCTALIA STARSHIP PALETTE <<<
