$primary = rgb(f0b0ff)
$surface = rgb(151215)
$secondary = rgb(d5c0d6)
$error = rgb(ffb4ab)
$tertiary = rgb(f5b7b2)
$surface_lowest = rgb(100d10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
